-- The compliance vocabularies as shipped.
--
-- Reference data belongs in a migration, not a script somebody remembers to run: without these
-- rows every compliance dropdown on the product card is empty and the eligibility rules have no
-- voltage ranges to compare, so the feature would deploy switched off.
--
-- ON CONFLICT DO NOTHING keeps it idempotent and, more importantly, non-destructive: a label
-- someone has reworded or a value they have retired must survive the next deploy.

INSERT INTO "compliance_option" ("kind", "code", "label", "numeric_min", "numeric_max", "note", "sort_order", "updated_at")
VALUES
  ('BATTERY_TYPE', 'NONE', 'No battery', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP),
  ('BATTERY_TYPE', 'ALKALINE', 'Alkaline (AA, AAA, 9V)', NULL, NULL, NULL, 10, CURRENT_TIMESTAMP),
  ('BATTERY_TYPE', 'LI_ION', 'Lithium-ion, rechargeable', NULL, NULL, 'UN3480 loose, UN3481 in or with equipment.', 20, CURRENT_TIMESTAMP),
  ('BATTERY_TYPE', 'LI_METAL', 'Lithium metal, non-rechargeable', NULL, NULL, 'UN3090 loose, UN3091 in or with equipment.', 30, CURRENT_TIMESTAMP),
  ('BATTERY_TYPE', 'LI_POLYMER', 'Lithium polymer', NULL, NULL, NULL, 40, CURRENT_TIMESTAMP),
  ('BATTERY_TYPE', 'BUTTON_CELL', 'Button or coin cell', NULL, NULL, 'Child-safety rules apply in several markets.', 50, CURRENT_TIMESTAMP),
  ('BATTERY_TYPE', 'NIMH', 'Nickel-metal hydride (NiMH)', NULL, NULL, NULL, 60, CURRENT_TIMESTAMP),
  ('BATTERY_TYPE', 'NICD', 'Nickel-cadmium (NiCd)', NULL, NULL, NULL, 70, CURRENT_TIMESTAMP),
  ('BATTERY_TYPE', 'LEAD_ACID', 'Lead-acid', NULL, NULL, NULL, 80, CURRENT_TIMESTAMP),
  ('BATTERY_TYPE', 'BUILT_IN', 'Built-in rechargeable, not user-replaceable', NULL, NULL, NULL, 90, CURRENT_TIMESTAMP),
  ('FREQUENCY', '50', '50 Hz', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP),
  ('FREQUENCY', '60', '60 Hz', NULL, NULL, NULL, 10, CURRENT_TIMESTAMP),
  ('FREQUENCY', '50/60', '50/60 Hz', NULL, NULL, NULL, 20, CURRENT_TIMESTAMP),
  ('FREQUENCY', 'DC', 'DC', NULL, NULL, NULL, 30, CURRENT_TIMESTAMP),
  ('FREQUENCY', 'NA', 'Not applicable', NULL, NULL, NULL, 40, CURRENT_TIMESTAMP),
  ('HAZMAT_CLASS', 'NONE', 'Not dangerous goods', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP),
  ('HAZMAT_CLASS', 'UN3480', 'UN3480 — lithium-ion batteries shipped alone', NULL, NULL, NULL, 10, CURRENT_TIMESTAMP),
  ('HAZMAT_CLASS', 'UN3481', 'UN3481 — lithium-ion batteries in or with equipment', NULL, NULL, NULL, 20, CURRENT_TIMESTAMP),
  ('HAZMAT_CLASS', 'UN3090', 'UN3090 — lithium metal batteries shipped alone', NULL, NULL, NULL, 30, CURRENT_TIMESTAMP),
  ('HAZMAT_CLASS', 'UN3091', 'UN3091 — lithium metal batteries in or with equipment', NULL, NULL, NULL, 40, CURRENT_TIMESTAMP),
  ('HAZMAT_CLASS', 'CLASS_1', 'Class 1 — Explosives', NULL, NULL, NULL, 50, CURRENT_TIMESTAMP),
  ('HAZMAT_CLASS', 'CLASS_2_1', 'Class 2.1 — Flammable gases (aerosols)', NULL, NULL, NULL, 60, CURRENT_TIMESTAMP),
  ('HAZMAT_CLASS', 'CLASS_2_2', 'Class 2.2 — Non-flammable, non-toxic gases', NULL, NULL, NULL, 70, CURRENT_TIMESTAMP),
  ('HAZMAT_CLASS', 'CLASS_2_3', 'Class 2.3 — Toxic gases', NULL, NULL, NULL, 80, CURRENT_TIMESTAMP),
  ('HAZMAT_CLASS', 'CLASS_3', 'Class 3 — Flammable liquids (alcohol, solvents, perfume)', NULL, NULL, NULL, 90, CURRENT_TIMESTAMP),
  ('HAZMAT_CLASS', 'CLASS_4_1', 'Class 4.1 — Flammable solids', NULL, NULL, NULL, 100, CURRENT_TIMESTAMP),
  ('HAZMAT_CLASS', 'CLASS_4_2', 'Class 4.2 — Spontaneously combustible', NULL, NULL, NULL, 110, CURRENT_TIMESTAMP),
  ('HAZMAT_CLASS', 'CLASS_4_3', 'Class 4.3 — Dangerous when wet', NULL, NULL, NULL, 120, CURRENT_TIMESTAMP),
  ('HAZMAT_CLASS', 'CLASS_5_1', 'Class 5.1 — Oxidising substances', NULL, NULL, NULL, 130, CURRENT_TIMESTAMP),
  ('HAZMAT_CLASS', 'CLASS_5_2', 'Class 5.2 — Organic peroxides', NULL, NULL, NULL, 140, CURRENT_TIMESTAMP),
  ('HAZMAT_CLASS', 'CLASS_6_1', 'Class 6.1 — Toxic substances', NULL, NULL, NULL, 150, CURRENT_TIMESTAMP),
  ('HAZMAT_CLASS', 'CLASS_6_2', 'Class 6.2 — Infectious substances', NULL, NULL, NULL, 160, CURRENT_TIMESTAMP),
  ('HAZMAT_CLASS', 'CLASS_7', 'Class 7 — Radioactive material', NULL, NULL, NULL, 170, CURRENT_TIMESTAMP),
  ('HAZMAT_CLASS', 'CLASS_8', 'Class 8 — Corrosive substances', NULL, NULL, NULL, 180, CURRENT_TIMESTAMP),
  ('HAZMAT_CLASS', 'CLASS_9', 'Class 9 — Miscellaneous dangerous goods', NULL, NULL, NULL, 190, CURRENT_TIMESTAMP),
  ('PLUG_TYPE', 'G', 'Type G — UK, Ireland, Malta, Cyprus', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP),
  ('PLUG_TYPE', 'F', 'Type F — Schuko: Germany, Netherlands, Spain, Sweden, Poland', NULL, NULL, NULL, 10, CURRENT_TIMESTAMP),
  ('PLUG_TYPE', 'C', 'Type C — Europlug, fits most of continental Europe', NULL, NULL, NULL, 20, CURRENT_TIMESTAMP),
  ('PLUG_TYPE', 'E', 'Type E — France, Belgium, Poland, Czechia', NULL, NULL, NULL, 30, CURRENT_TIMESTAMP),
  ('PLUG_TYPE', 'L', 'Type L — Italy, Chile', NULL, NULL, NULL, 40, CURRENT_TIMESTAMP),
  ('PLUG_TYPE', 'J', 'Type J — Switzerland, Liechtenstein', NULL, NULL, NULL, 50, CURRENT_TIMESTAMP),
  ('PLUG_TYPE', 'K', 'Type K — Denmark, Greenland', NULL, NULL, NULL, 60, CURRENT_TIMESTAMP),
  ('PLUG_TYPE', 'A', 'Type A — US, Canada, Japan (ungrounded)', NULL, NULL, NULL, 70, CURRENT_TIMESTAMP),
  ('PLUG_TYPE', 'B', 'Type B — US, Canada, Japan (grounded)', NULL, NULL, NULL, 80, CURRENT_TIMESTAMP),
  ('PLUG_TYPE', 'I', 'Type I — Australia, New Zealand, China, Argentina', NULL, NULL, NULL, 90, CURRENT_TIMESTAMP),
  ('PLUG_TYPE', 'D', 'Type D — India, Nepal, Sri Lanka', NULL, NULL, NULL, 100, CURRENT_TIMESTAMP),
  ('PLUG_TYPE', 'M', 'Type M — South Africa', NULL, NULL, NULL, 110, CURRENT_TIMESTAMP),
  ('PLUG_TYPE', 'N', 'Type N — Brazil, South Africa', NULL, NULL, NULL, 120, CURRENT_TIMESTAMP),
  ('PLUG_TYPE', 'H', 'Type H — Israel', NULL, NULL, NULL, 130, CURRENT_TIMESTAMP),
  ('PLUG_TYPE', 'O', 'Type O — Thailand', NULL, NULL, NULL, 140, CURRENT_TIMESTAMP),
  ('PLUG_TYPE', 'USB', 'USB powered', NULL, NULL, NULL, 150, CURRENT_TIMESTAMP),
  ('PLUG_TYPE', 'HARDWIRED', 'Hardwired / no plug', NULL, NULL, NULL, 160, CURRENT_TIMESTAMP),
  ('PLUG_TYPE', 'NONE', 'No mains connection', NULL, NULL, NULL, 170, CURRENT_TIMESTAMP),
  ('VOLTAGE_RATING', '220-240V', '220–240V (EU/UK/AU)', 220, 240, NULL, 0, CURRENT_TIMESTAMP),
  ('VOLTAGE_RATING', '100-120V', '100–120V (US/CA/JP)', 100, 127, NULL, 10, CURRENT_TIMESTAMP),
  ('VOLTAGE_RATING', '100-240V', '100–240V (dual voltage, worldwide)', 100, 240, 'Sellable on every market — the usual answer for chargers and power supplies.', 20, CURRENT_TIMESTAMP),
  ('VOLTAGE_RATING', '230V', '230V only', 230, 230, NULL, 30, CURRENT_TIMESTAMP),
  ('VOLTAGE_RATING', '110V', '110V only', 110, 110, NULL, 40, CURRENT_TIMESTAMP),
  ('VOLTAGE_RATING', '12V-DC', '12V DC', 12, 12, NULL, 50, CURRENT_TIMESTAMP),
  ('VOLTAGE_RATING', '24V-DC', '24V DC', 24, 24, NULL, 60, CURRENT_TIMESTAMP),
  ('VOLTAGE_RATING', 'BATTERY', 'Battery powered only', NULL, NULL, 'No mains connection, so no market is excluded on voltage.', 70, CURRENT_TIMESTAMP),
  ('VOLTAGE_RATING', 'NONE', 'Not electrical', NULL, NULL, NULL, 80, CURRENT_TIMESTAMP)
ON CONFLICT ("kind", "code") DO NOTHING;
